language: ruby
rvm:
  - 2.1.3
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - RAILS_ENV=test bundle exec rspec spec

bundler_args: --path vendor/bundle --without test --without documentation

addons:
  postgresql: "9.3"

services:
  - postgresql

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.travis.yml config/secrets.yml
  - psql -c 'create database quizz_test;' -U postgres
